# Generated by Django 4.1 on 2022-08-24 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slices', '0005_remove_payment_id_alter_payment_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
